---
title: "logistic regression"
author: "Tianyue Xiao"
date: "2022-12-6"
output: html_document
---


**Write the dataframe into csv file**

```{r}
filename = "data_predict.csv"
write.csv(data_reduced, filename, row.names = FALSE)
```

**Logistic regression**
```{r}
require(ISLR)
iris_binary=iris[iris$B_avg_SUB_ATT!=" ",]
modle=glm(B_avg_SUB_ATT ~ Sepal.Length, data = iris_binary, family = binomial)
summary(modle)
predicted=ifelse(predict(modle, type = "response")>.5," "," ")

# Build a for loop to show how FPR and TPR jointly change as you modify the threshold of
# 0.5. seq(0.01, 0.99, 0.005)
thresholds = seq(0.01, 0.99, 0.005)
TPR = numeric(length(thresholds))
FPR = numeric(length(thresholds))

for (i in 1:length(thresholds)) {
  predicted = factor(
    ifelse(predict(
      logreg, type = "response")>thresholds[i]," ", " "),
                      levels = c(' ', ' '))
  confusion = table(as.character(iris_binary$Species),
                     predicted,
                     dnn = c(" ", " "))
  TPR[i] = confusion[2,2]/(confusion[2,2]+confusion[2,1])
  FPR[i] = confusion[1,2]/(confusion[1,2]+confusion[1,1]) # False positive rate:
}

head(cbind(thresholds, TPR, FPR))
tail(cbind(thresholds, TPR, FPR))
plot(x=FPR,y=TPR, type='l', main = 'Curve')
```


```{r}
mydata <- read.csv("/Users/THESUN/Downloads/141A-final-project-main/ufc_data.csv")
head(mydata)
mydata$ "变量" <-factor(mydata$"变量",labels = c("",""))
mydata$"变量" <-factor(mydata$"变量",labels = c("","","")) 
#判断线性关系#
library(ggplot2)
ggplot(data=mydata,aes(x=Fasting.insulin,y=FBS))+geom_point()+stat_smooth(method="lm",se=TRUE) #变量1与变量2的关系
#然后解读结果，“变量1”、“变量2”与因变量之间有没有纯在线性关系
```


```{r}
#判断独立性#
library(car)
durbinWatsonTest(lm(变量~,data=mydata))
```

```{r}
lm.reg<-lm(变量,data=mydata) 合回归分析
cook<-cooks.distance(lm.reg) #计算cook距离
cook[cooks.distance(lm.reg)>0.5] #显示cook距离>0.5的和cook值
max(cook) #显示最大cook距离
```


```{r}
#判断(多重共线性判断)
vif(lm.reg)
#如果自变量的VIF均<10，说明自变量之间不存在共线性问题
```
```{r}
shapiro.test(lm.reg$residuals)
qqnorm(lm.reg$residuals)
qqline(lm.reg$residuals)
#看qqplot有没有服从正太分布
```

